---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: counter
spec:
  template:
    metadata:
      labels:
        taranto.dev/app: simple-http
        taranto.dev/app.simple-http.role: counter
      annotations:
        diamanti.com/endpoint0: '{"network":"default","perfTier":"low"}'
    spec:
      containers:
      - name: counter
        image: staranto/simple-http-counter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
          name: http
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /live
            port: 8282
          initialDelaySeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8282
          initialDelaySeconds: 3
      restartPolicy: Always
  replicas: 1
...
---
apiVersion: v1
kind: Service
metadata:
  name: counter
  labels:
    taranto.dev/app: simple-http
    taranto.dev/app.simple-http.role: counter-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    taranto.dev/app.simple-http.role: counter
...
